// This file will be auto-generated by Supabase CLI
// Run: pnpm generate-types (after setting SUPABASE_PROJECT_ID)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Tables will be generated here by Supabase CLI
    };
    Views: {
      // Views will be generated here
    };
    Functions: {
      // Functions will be generated here
    };
    Enums: {
      // Enums will be generated here
    };
  };
}
